version: '3.4'

services:
  web:
    build: .
    links:
      - db
    volumes:
      - .:/data
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0-oracle
    environment:
      - MYSQL_USER=aluno
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=loja
    ports:
      - "3306:3306"
